### ISSUE TITLE
Sort by Date

### ISSUE THREAD

**Issue by Taurean75** [lutostag/webextension-formsave#10]
Since it's alphanumeric, it doesn't sort correctly. It should sort internally using timestamps instead.

Thanks.

**Comment by lutostag** [comment]
Thanks for filling this bug. I know there was (and still is in the latest version) an issue that we were sorting on a non-existent key called `date` I switched it to the correct key `time` in 012b40b0bfe200e94d6bdf481afd64da3f4dfe6c.

You are seeing that the date sort is wrong, but the other columns are correct?

I will see if I can release a new build with the fix to make sure that was actually the issue.

Thanks @Taurean75

**Comment by Taurean75** [comment]
Otters are correct.

It'd be nice if columns could be resized.

**Comment by Taurean75** [comment]
@lutostag: Any updates?

**Comment by lutostag** [comment]
@Taurean75 thanks for the ping.

My current dev machine is in a bad state. I think the current master branch is ready for a release. Will submit one to AMO soon. Probably this weekend.

**Comment by lutostag** [comment]
Released v0.9.14, it has the fix to sort correctly. Please give it a shot!

In addition I have opened https://github.com/lutostag/webextension-formsave/issues/11 for the resizing columns request. Thanks for that too.

Feel free to re-open if the latest release does not resolve your issue.
