### ISSUE TITLE
Availlable in the ChromeStore ?

### ISSUE THREAD

**Issue by mikhoul** [lutostag/webextension-formsave#17]
I'm migrating slowly from Firefox to Chromium since Mozilla restrict more and more things for power users and I did not found your addons in the ChromeStore.

I've seen the CRX but since I'm new with Chromium it's would be more quick/easy to install the addon than sideloading it, does the addon have the same name in the Chromestore ?  

You should add a link to the ChromeStore in the description.

**Regards and thanks for this very useful addon** :octocat:

**Comment by lutostag** [comment]
It is not currently on the chrome store.

I have held off doing so for a few reasons:
* Chrome(ium) in most cases forces addons to only be installed from the chrome store (only exception being on Linux versions), which additionally requires a one-time payment of $5 via credit-card seems a bit strange, and not entirely friendly...
* I do use the chromium browser on occasion when forced to and have taken the time to package it for chrome(ium) with auto-updating, but prefer to promote Firefox or other non-google browsers (to fight against their dominant market share, that I think in the long run is harmful to the competition necessary to promote a neutral Internet), I will have to see the compatibility with other browsers webextension support.

I realize I am swimming against a fast-moving current, and for this small-addon it doesn't seem like much.

Furthermore, I am not totally against the idea, just for the reasons above I haven't jumped through those hurdles yet.

I will take some time to think longer on the subject.

Thanks for using it (and providing valuable feedback too!). And if the instructions for installing in chrome(ium) are incomplete/confusing. Please let me know and I will have a look at improving them.

**Comment by lutostag** [comment]
As a clarification, I do not intend the above as an attack on your browser choice. I know chrome(ium) is a wonderful browser, just the ecosystem around it gives me pause to support that system in general.

**Comment by mikhoul** [comment]
I understand your point of view entirely and I agree with you, 

I'm shifting from Firefox slowly because I'm feed up from Mozilla answers to power-users in general. Right now I'm using Firefox 56.02 with over 85 addons and more than 25 Userscripts .

I was considering maybe using Firefox again even past FF 56 but Mozilla irresponsible/shaddy decisions since last September make it more easy for me to shift to Chromium for my daily browser.

The AMO store is becoming more and more like the crappy Chrome store with no verification and removing users options for nothing deliberately, they will also remove old xul addon from AMO in July and so many other nonsensical decisions.

I'm feed up to constantly change version after version my workflow just because of Mozilla crazy decisions, it is a way for me to protest about Mozilla corporate capitalist vision/decision.

Chrome as of now for me is lot faster, more stable and have the same addon-choice than Mozilla post version 56 and moreover it is more stable with no crazy change at each new release. 

I will use Firefox but only mainly for the Dev Tools not really for browsing. I just hope with Firefox that the users numbers will go so low and near to zero that positive changes will happen in the culture at Mozilla.

Maybe one day I will be back but for now Firefox as no appeal for me, I changed in the last year over 100 users from Firefox to Chrome in my business since it's for casual users as of now it's lot more stable and no surprise at each releases. 

Today they are doing only cosmetic change and removing capabilities in Firefox to make it a dumb browsers and during this time they let REAL BUGS pile up....and sadly don't care about them and label them "wontfix".  

Sorry for my rant :wink: 

I will explore more in deep  how to side-load efficiently addons in Chromium, like Firefox I know that if you use Dev build (Canary) there is less restriction to load your own addon.... I'm pretty sure that like with Firefox there is some workaround to make it less painful for power users.

I  will let you know when I will find a way to make it more easy, I need it since I tweak lot of addons for my need or to fix them when they are abandoned.

_**Thanks again for your quick answer**_ @lutostag  :octocat:

**Comment by mikhoul** [comment]
@lutostag   I found a very interesting thread about the change in Chromium 63 about the installation of extension that are not in the CWS (signed) : https://bugs.chromium.org/p/chromium/issues/detail?id=794219

I have not finished to read it but it seem it will have the answers I was looking for.

For now my take is that I will have to make a .reg file for Windows to whitelist (**ExtensionInstallWhitelist**) the addon I want to use that are not in the CWS. It should not be to hard to do and maintain if you want to have more information about the format for the registry and the key to create edit look here: https://www.chromium.org/administrators/policy-list-3

I could also use some Chrome Administrative Templates but for me it will be more easy and convenient with .reg file to make the required changes.

Regards :octocat:

**Comment by lutostag** [comment]
Hmm, that is interesting. Thanks for the info, I looked but couldn't find that.

I am a bit concerned about
> Use of these policies outside of your organization (for example, in a publicly distributed program) is considered malware and will likely be labeled as malware by Google and anti-virus vendors.

I also do not have a windows nor Mac machine to test on, but I will try to come up with a `.reg` file or similar to try it out. If it works well I will upload here with some documentation about how to better install.

Not sure on the timeline on this. Thanks for filling the bug though.

Appreciate it.

**Comment by mikhoul** [comment]
After looking at many way to use Chrome extensions that are not in the store I've found the more convenient way for me is just to unpack the addon in a folder and use the chrome://extensions and press the button **"Load unpacked extension"**. 

Many other devs that don't want to publish in the "_Chrome Web Store_" like you just put a link from their website or from their Githb repo to the zip file and show with a short tutorial how to load extension that are not from the _Chrome Web Store_ .

https://i.imgur.com/tvg09fD.png


Regards :octocat:
