### ISSUE TITLE
allow exporting of saved forms

### ISSUE THREAD

**Issue by lutostag** [lutostag/webextension-formsave#8]
Have a button on the options page to export to a file.

I would like to know more about the use-case for this, and what format may be best.

JSON would be easy but not the prettiest. Or it could be tab separated. I am curious how you will use it, so I can make a better-informed decision about which will be better for you as a user.

This comment originally taken from the AMO page. Thanks Fornit!

**Comment by Taurean75** [comment]
JSON would be okay with me.

**Comment by lutostag** [comment]
Implemented in ffecf52a1085b9e63645edf34f44897ce61fd533
